### ISSUE TITLE
Can supertest be called in the pre test hooks?

### ISSUE THREAD

**Issue by reallymello** [nightwatchjs/nightwatch-plugin-apitesting#4]
How would one pass in the supertest object to the before / beforeEach test hooks to call an endpoint to get something like an authentication token before running the actual tests?

**Comment by beatfactor** [comment]
I guess you can use `supertest` module directly in a `before` hook. In the `beforeEach` you also have the `browser` object available.

**Comment by reallymello** [comment]
Yep, something like this worked

```js
  before: async (client: NightwatchBrowser) => {
    await client.supertest
      .request(baseUrl)
      .post('/auth')
      .send({
        username: 'admin',
        password: 'password123',
      })
      .expect(200)
      .expect('Content-type', 'application/json; charset=utf-8')
      .then((response: any) => {
        authToken = response.body;
      });
  },
```
